# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_used', models.CharField(max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSkillList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_used', models.ManyToManyField(through='projects.ProjectSkill', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='projectskill',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Skill'),
        ),
        migrations.AddField(
            model_name='projectskill',
            name='skill_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.ProjectSkillList'),
        ),
    ]
